source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def pods
    pod 'Alamofire'
    pod 'SwiftyJSON'
end

target 'Users' do
    pods
end

target 'UsersTests' do
    pods
end

